import React, { useState, useEffect } from 'react';
import { HelpCircle, Plus } from 'lucide-react';
import InfoBox from '../InfoBox';
import { Paperless } from '@/api/entities';
import { useLanguage } from '@/contexts/LanguageContext';
import FormInput from '@/components/FormInput';

export default function StaticDataStep({ 
  ruleData, 
  updateRuleData, 
  showInfoBoxes, 
  setShowInfoBoxes 
}) {
  const { t } = useLanguage();
  const [correspondents, setCorrespondents] = useState([]);
  const [documentTypes, setDocumentTypes] = useState([]);
  const [availableTags, setAvailableTags] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadPaperlessData();
  }, []);

  const loadPaperlessData = async () => {
    try {
      const [corr, docTypes, tags] = await Promise.all([
        Paperless.getCorrespondents(),
        Paperless.getDocumentTypes(),
        Paperless.getTags()
      ]);
      setCorrespondents(corr.map(c => c.name).sort());
      setDocumentTypes(docTypes.map(dt => dt.name).sort());
      setAvailableTags(tags.map(t => t.name).sort());
    } catch (error) {
      console.error('Error loading Paperless data:', error);
    } finally {
      setIsLoading(false);
    }
  };
  const addTag = (tag) => {
    const currentTags = ruleData.predefinedData?.tags || [];
    if (tag && !currentTags.includes(tag)) {
      const newTags = [...currentTags, tag];
      updateRuleData('predefinedData', { tags: newTags });
    }
  };

  const removeTag = (index) => {
    const currentTags = ruleData.predefinedData?.tags || [];
    const newTags = currentTags.filter((_, i) => i !== index);
    updateRuleData('predefinedData', { tags: newTags });
  };

  return (
    <div className="wizard-container">
      <div className="flex items-center gap-2 mb-6" style={{minHeight: '32px'}}>
        <h2 className="text-2xl font-bold">{t('wizard.step3Title')}</h2>
        {!showInfoBoxes[3] && (
          <button 
            onClick={() => setShowInfoBoxes(prev => ({ ...prev, 3: true }))}
            className="btn btn-ghost btn-sm p-1"
            style={{ color: 'var(--app-text-muted)' }}
            onMouseEnter={(e) => e.currentTarget.style.color = 'var(--app-text-secondary)'}
            onMouseLeave={(e) => e.currentTarget.style.color = 'var(--app-text-muted)'}
          >
            <HelpCircle className="w-4 h-4" />
          </button>
        )}
      </div>
      <p className="mb-6" style={{ color: 'var(--app-text-secondary)' }}>
        {t('wizard.staticDataDescription')}
      </p>

      <InfoBox 
        stepNumber={3}
        showInfoBoxes={showInfoBoxes}
        setShowInfoBoxes={setShowInfoBoxes}
      >
        <div>
          <h4 className="font-semibold text-sm mb-1">{t('wizard.staticClassificationDataInfoTitle')}</h4>
          <p className="text-sm">
            {t('wizard.staticClassificationDataInfoText')}
          </p>
        </div>
      </InfoBox>

      <div className="space-y-6">
        <div className="form-group">
          <label className="form-label">{t('fields.title')}</label>
          <FormInput
            type="text"
            disabled
            placeholder={t('placeholders.autoGeneratedFromDoc')}
            className="cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.archiveSerialNumber')}</label>
          <FormInput
            type="text"
            disabled
            placeholder={t('placeholders.autoGenerated')}
            className="cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.dateCreated')}</label>
          <FormInput
            type="text"
            disabled
            placeholder={t('placeholders.autoGenerated')}
            className="cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.correspondent')}</label>
          {isLoading ? (
            <div className="pc-input" style={{ backgroundColor: 'var(--app-bg-secondary)' }}>{t('fields.loading')}</div>
          ) : (
            <select
              value={ruleData.predefinedData?.correspondent || ''}
              onChange={(e) => updateRuleData('predefinedData', { correspondent: e.target.value })}
              style={{
                borderColor: 'var(--input-border, #d1d5db)',
                borderWidth: '1px',
                backgroundColor: 'var(--input-bg, #ffffff)',
                color: 'var(--input-text, #111827)',
                width: '100%',
                padding: '8px 12px',
                borderRadius: '4px',
                fontSize: '1rem',
              }}
              className="transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">{t('fields.selectCorrespondent')}</option>
              {correspondents.map(corr => (
                <option key={corr} value={corr}>{corr}</option>
              ))}
            </select>
          )}
          <p className="text-xs mt-1" style={{ color: 'var(--app-text-muted)' }}>
            {correspondents.length > 0 ? t('fields.correspondentsAvailable', { count: correspondents.length }) : t('fields.noCorrespondentsFound')}
          </p>
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.documentType')}</label>
          {isLoading ? (
            <div className="pc-input" style={{ backgroundColor: 'var(--app-bg-secondary)' }}>{t('fields.loading')}</div>
          ) : (
            <select
              value={ruleData.predefinedData?.documentType || ''}
              onChange={(e) => updateRuleData('predefinedData', { documentType: e.target.value })}
              style={{
                borderColor: 'var(--input-border, #d1d5db)',
                borderWidth: '1px',
                backgroundColor: 'var(--input-bg, #ffffff)',
                color: 'var(--input-text, #111827)',
                width: '100%',
                padding: '8px 12px',
                borderRadius: '4px',
                fontSize: '1rem',
              }}
              className="transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">{t('fields.selectDocumentType')}</option>
              {documentTypes.map(dt => (
                <option key={dt} value={dt}>{dt}</option>
              ))}
            </select>
          )}
          <p className="text-xs mt-1" style={{ color: 'var(--app-text-muted)' }}>
            {documentTypes.length > 0 ? t('fields.documentTypesAvailable', { count: documentTypes.length }) : t('fields.noDocumentTypesFound')}
          </p>
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.storagePath')}</label>
          <FormInput
            type="text"
            disabled
            placeholder={t('placeholders.autoGeneratedRules')}
            className="cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.tags')}</label>
          <div className="flex gap-2 mb-2">
            <FormInput
              type="text"
              placeholder={t('placeholders.addTag')}
              className="flex-1"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && e.target.value.trim()) {
                  e.preventDefault();
                  addTag(e.target.value.trim());
                  e.target.value = '';
                }
              }}
            />
            <button 
              onClick={(e) => {
                const input = e.target.parentElement.querySelector('input');
                if (input.value.trim()) {
                  addTag(input.value.trim());
                  input.value = '';
                }
              }}
              className="btn btn-secondary"
            >
              {t('common.add')}
            </button>
          </div>
          {availableTags.length > 0 && (
            <div className="mb-2">
              <p className="text-xs mb-1" style={{ color: 'var(--app-text-muted)' }}>{t('fields.suggestedTags')}</p>
              <div className="flex flex-wrap gap-1">
                {availableTags.slice(0, 10).map(tag => (
                  <button
                    key={tag}
                    onClick={() => addTag(tag)}
                    className="px-2 py-1 text-xs rounded"
                    style={{ backgroundColor: 'var(--info-bg)', color: 'var(--info-text)' }}
                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--info-border)'}
                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--info-bg)'}
                    type="button"
                  >
                    + {tag}
                  </button>
                ))}
              </div>
            </div>
          )}
          <div className="flex flex-wrap gap-2">
            {(ruleData.predefinedData?.tags || []).map((tag, index) => (
              <span key={index} className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm" style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text)' }}>
                {tag}
                <button 
                  onClick={() => removeTag(index)}
                  className="hover:text-red-500"
                  style={{ color: 'var(--app-text-muted)' }}
                  type="button"
                >
                  ×
                </button>
              </span>
            ))}
          </div>
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.customField')}</label>
          <input
            type="text"
            placeholder={t('placeholders.definedPaperless')}
            className="pc-input"
          />
          <p className="text-xs text-gray-500 mt-1">{t('fields.customFieldsPredefinedNote')}</p>
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.documentCategory')}</label>
          <input
            type="text"
            value={ruleData.predefinedData?.documentCategory || ''}
            onChange={(e) => updateRuleData('predefinedData', { documentCategory: e.target.value })}
            placeholder={t('placeholders.exampleFinancial')}
            className="pc-input"
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.pocoScore')}</label>
          <input
            type="text"
            disabled
            placeholder={t('placeholders.autoCalculated')}
            className="pc-input cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">{t('fields.pocoOcr')}</label>
          <input
            type="text"
            disabled
            placeholder={t('placeholders.autoPopulated')}
            className="pc-input cursor-not-allowed"
            style={{ backgroundColor: 'var(--app-bg-secondary)', color: 'var(--app-text-secondary)' }}
          />
        </div>
      </div>
    </div>
  );
}